[package]
name = "crabchess"
version = "0.1.0"
edition = "2018"
authors = ["Clayton Ramsey"]

[profile.test]
debug = true
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[profile.release]
opt-level = 3
# debug = true