[workspace]

members = [
    "base",
    "engine",
    "tuner",
    "cli",
]

[profile.test]
debug = true
# must be highly optimized for speed, since searching and perft is done in tests
opt-level = 3 

[profile.release]
opt-level = 3
lto = true
debug = 1 # used for profiling