[package]
name = "fiddler_engine"
version = "0.1.0"
edition = "2018"
authors = ["Clayton Ramsey"]
default-run = "fiddler_engine"

[lib]

[dependencies]
fiddler_base = {path = "../base"}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html